name: task
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  smooth_star_rating: ^1.0.3
  provider: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo.jpg
    - assets/images/logo.png
    - assets/images/slider/bdla.jpg
    - assets/images/slider/kames.jpg
    - assets/images/slider/tro.jpg
    - assets/images/recentPro/1.jpg
    - assets/images/recentPro/2.jpg
    - assets/images/recentPro/3.jpg
    - assets/images/recentPro/4.jpg
    - assets/images/recentPro/5.jpg
    - assets/images/brands/H&M.jpg
    - assets/images/brands/POLO.jpg
    - assets/images/brands/ZARA.png
    - assets/images/pink.jpg
    - assets/images/icons/troIcon.jpg
    - assets/images/icons/bdalIcon.jpg
    - assets/images/icons/kamesIcon.png
    - assets/images/sad.png
    - assets/images/zara/1.jpg
    - assets/images/zara/2.jpg
    - assets/images/zara/3.jpg
    - assets/images/zara/4.jpg
    - assets/images/zara/5.jpg
    - assets/images/zara/lo.png
    - assets/images/H&M/1.jfif
    - assets/images/H&M/2.jfif
    - assets/images/H&M/3.jfif
    - assets/images/H&M/4.jfif
    - assets/images/H&M/5.jfif
    - assets/images/Polo/1.jfif
    - assets/images/Polo/2.jfif
    - assets/images/Polo/3.jfif
    - assets/images/Polo/4.jfif
    - assets/images/Polo/5.jfif
    - assets/images/icons/childIcon.png
    - assets/images/sections/tro/1.jfif
    - assets/images/sections/tro/2.jfif
    - assets/images/sections/tro/3.jfif
    - assets/images/sections/suit/1.jfif
    - assets/images/sections/suit/2.jfif
    - assets/images/sections/suit/3.jfif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
